@echo off
echo Installing requirements...
python -m pip install -r backend\requirements.txt
echo Generating mock data...
python dataset\mock_generator.py
echo Starting server...
python -m uvicorn backend.main:app --reload
pause
